revamped moderation system and minor bug fixes
a801-luadev/parkour pull request #68
Opened 2023-07-02 12:57 UTC by mckeydown

2023-07-04 00:38 UTC, Tocutoeltuco requested changes

2023-07-04 00:38 UTC, tocuto commented on modes/parkour/game.lua
> +	if player:sub(1,1) ~= "*" then
Why are you not counting souris accounts? Is there any other protection in place?

2023-07-04 00:38 UTC, tocuto commented on modes/parkour/maps.lua
> +		checkMapBug()
A timer would be a better fit here:
```lua
local checkMapBug
function checkMapBug()
  ...
  addNewTimer(5000, checkMapBug)
end
checkMapBug()
```

2023-07-04 00:38 UTC, tocuto commented on modes/parkour/moderation.lua
> +	data = filemanagers[file]:load(data)
This will most definitely parse the file multiple times. Try using the GameDataLoaded event, which happens when a file is parsed.

2023-07-04 00:38 UTC, Tocutoeltuco commented on modes/parkour/moderation.lua
> +	eventGameDataLoaded(data)
This will definitely trigger GameDataLoaded twice.

2023-07-04 00:38 UTC, Tocutoeltuco commented on modes/parkour/moderation.lua
> +		eventSavingFile(tostring(file), data)
And you're also saving the file twice. I'd recommend editing `files.lua` at this point.

2023-07-04 00:38 UTC, Tocutoeltuco commented on modes/parkour/moderation.lua
Is this some sort of copy of the bots mode? I'd recommend removing it then.

2023-07-04 00:38 UTC, Tocutoeltuco commented on modes/parkour/moderation.lua
> +function in_table(value, tbl)
Do remember using `local` for function declarations.

2023-07-04 00:38 UTC, Tocutoeltuco commented on modes/parkour/maps.lua
> +function checkMapBug()
Do remember using `local` for function declarations.

2023-07-04 00:38 UTC, Tocutoeltuco commented on modes/parkour/moderation.lua
> +		tfm.exec.chatMessage("<v>[#] <r>"..player.. " must have joined any parkour room after the last update. [v"..data.v.."]", requester)
I'd recommend simply treating this case as the user being offline: write the ban to a file and it'll get applied eventually.

2023-07-04 00:38 UTC, Tocutoeltuco commented on modes/parkour/moderation.lua
> +		if data.banned and (data.banned == 2 or os.time() < data.banned) then tfm.exec.chatMessage("<v>[#] <r>"..player.. " has already banned.", requester) return end
This is a weirdly long condition. I'd recommend unwrapping it.

2023-07-04 00:38 UTC, Tocutoeltuco commented on modes/parkour/moderation.lua
> +			data.bancount = data.bancount + 1
Why is this indented one extra level than the one it should be?

2023-07-04 00:38 UTC, Tocutoeltuco commented on modes/parkour/moderation.lua
> +				data.banned = os.time()+tonumber((data.bancount)*1440)*60*1000
tonumber() is unnecessary here.

2023-07-04 00:38 UTC, Tocutoeltuco commented on modes/parkour/moderation.lua
> +			system.loadPlayerData(args[1])
I recommend adding a ban-by-id command that will just write the ban to the file; for whenever the player is offline.

2023-07-04 00:38 UTC, Tocutoeltuco commented on modes/parkour/moderation.lua
> +				tfm.exec.chatMessage("<v>[#] <r>" ..playerid.. " has banned for " ..(tonumber(args[2])).. " minutes", player)
There seems to be too much repeated code. Have you considered splitting it into functions?

2023-07-04 00:38 UTC, Tocutoeltuco commented on modes/parkour/moderation.lua
> +			if in_table(mapcode, maps.list_low) then
Careful: The list might be outdated.
I'd recommend simply doing this check whenever the maps file loads.

2023-07-04 00:38 UTC, Tocutoeltuco commented on modes/parkour/moderation.lua
> +			if in_table(mapcode, maps.list_low) then
(and simply merge both low_map_change and high_map_change, the file will determine whether that happens on low or high priority)

2023-07-04 00:38 UTC, Tocutoeltuco commented on modes/parkour/moderation.lua
> +			if not tonumber(args[1]) then
Weird indentation.

2023-07-04 00:38 UTC, Tocutoeltuco commented on modes/parkour/moderation.lua
> +end end)
where does the first end come from? please do fix the indentation 😩

2023-07-04 00:38 UTC, Tocutoeltuco commented on modes/parkour/moderation.lua
> +	system.disableChatCommandDisplay("setrank")
Maybe we could simply use `system.disableChatCommandDisplay(nil)` and remove all those nasty function calls?

2023-07-27 01:42 UTC, mckeydown commented on modes/parkour/maps.lua
> +		checkMapBug()
I think I can't use timer to check players position every 10 seconds

2023-07-27 14:06 UTC, Tocutoeltuco commented on modes/parkour/maps.lua
> +		checkMapBug()
Why not? That function would work perfectly; especially since parkour's timers rely on eventLoop and not on transformice's system.newTimer.

2023-07-28 03:39 UTC, mckeydown commented on modes/parkour/maps.lua
> +		checkMapBug()
The timer doesn't seem to be designed for loop and using a counter would be a simpler approach. 200+ addNewTimer calls during a round can potentially affect the runtime.

2023-07-29 14:46 UTC, Tocutoeltuco reviewed
While I will not request changes; this PR is not approved until we discuss the recommendations I gave you.

Also, do periodically check the #translations discord channel and add the translations whenever possible!

2023-07-29 14:46 UTC, tocuto commented on modes/parkour/filemanagers.lua
> +	["24"] = FileManager.new({
Why creating a separate ranking? Why not reusing file 21?

2023-07-29 14:46 UTC, Tocutoeltuco commented on modes/parkour/files.lua
> +		eventPlayerDataUpdated(player, old)
What is the point of this?

2023-07-29 14:46 UTC, Tocutoeltuco commented on modes/parkour/files.lua
> +	next_file_load = ts + math.random(10500, 30500)
I would *recommend* setting the upper limit to 15500, instead of 30500.

2023-07-29 14:46 UTC, Tocutoeltuco commented on modes/parkour/files.lua
> +		next_file_load = now + math.random(10500, 11000)
I would recommend setting the upper limit to 13000 instead of 11000.

2023-07-29 14:46 UTC, Tocutoeltuco commented on modes/parkour/filemanagers.lua
> +	["23"] = FileManager.new({
Why creating a new file? Why not reusing file 22?

2023-07-29 14:46 UTC, Tocutoeltuco commented on modes/parkour/leaderboard.lua
>  			end
I would recommend simply removing this; no big deal tho.

2023-07-29 14:46 UTC, Tocutoeltuco commented on modes/parkour/moderation.lua
> +		eventSavingFile(tostring(fileid), data)
Do remember we're already triggering eventSavingFile in `files.lua`. I don't really see any situation where both would be triggered *in this revision*; but as a safe guard and somewhat future proofing, I would simply remove one of the two and add a single place where it is called.

2023-07-29 14:46 UTC, Tocutoeltuco commented on translations/parkour/en.lua
> +	help_changelog = "<font size='13'><p align='center'><o>Version 2.12.0 - 26/07/2023</o></p>\n\n<font size='11'>• <font size='13'>The weekly ranking feature has been reinstated and is now available ag
I'd recommend changing this date to 31/07 or 01/08; as that is a more realistic release date.
I'll also ask translators to... translate lol

2023-07-29 14:46 UTC, Tocutoeltuco commented on modes/parkour/leaderboard.lua
> +	if not lwIndex and not cwIndex then return end
This seems a little resource intensive; changing it to a dictionary might help. I also thought it'd help to cleanup the file a little; but I'm not exactly sure whether or not you're doing it in another place.
```suggestion
	local id = tostring(room.playerList[player].id)
	if not weeklyfile.lw[id] and not weeklyfile.cw[id] then return end
	weeklyfile.lw[id] = nil
	weeklyfile.cw[id] = nil
```

```lua
{
	name = "cw",
	type = "dictionary",
	objects = {
		type = "boolean" 
	},
},
{
	name = "lw",
	type = "dictionary",
	objects = {
		type = "boolean" 
	},
},
```

2023-07-31 15:11 UTC, tocuto approved these changes
LGTM!

2023-07-31 15:11 UTC, merged